### ISSUE TITLE
Dependency URI Cannot Be Resolved

### ISSUE THREAD

**Issue by pivotal-david-osullivan** [paketo-buildpacks/apache-skywalking#78]
## Expected Behavior
Tests on main as well as builds with the latest version of this buildpack are failing due to the dependency for v8.16.0 not being available at `downloads.apache.org/skywalking/java-agent/`

## Current Behavior
The update-dependency action points to `downloads.apache`, which only has the latest version. This is now the new major v9, as per #77, so 8.x can no longer be found. 

## Possible Solution
We should probably update the [action](https://github.com/paketo-buildpacks/pipeline-builder/blob/5d237dc8168c5d9fba150b343d4dd8606d86bf35/actions/skywalking-dependency/main.go#L31C10-L31C60) to use the URI `https://archive.apache.org/dist/skywalking/java-agent/` where older versions are present along with the latest.
A further improvement might be to remove the hard-coded URI in the action and set it as an input, like other [similar](https://github.com/paketo-buildpacks/apache-tomcat/blob/main/.github/pipeline-descriptor.yml) actions.

**Comment by dmikusa** [comment]
@pivotal-david-osullivan I think this one is almost finished thanks to your recent commits. The one issue I see is that there's a double `//` in the URL. See https://github.com/paketo-buildpacks/apache-skywalking/pull/82/files.

I think this is coming from your commit here -> https://github.com/paketo-buildpacks/pipeline-builder/commit/b919b947bfda636fb892324694aa524fe1f3b500 That introduced a trailing slash on the URL.

**Comment by anthonydahanne** [comment]
@pivotal-david-osullivan already fixed that, see: https://github.com/paketo-buildpacks/pipeline-builder/commit/0dc3968707c73da761bf2e2a95cf44939e6d00ec#diff-f9795f77521e6356842f59638342b331da740d1502f22c3d544fa50cd9cdcde5R31

**Comment by anthonydahanne** [comment]
either of you @pivotal-david-osullivan or @dmikusa can you please close this issue. (I can't, for some reasons..)
thank you!
